#------------------- Default configuration --------------------------

FOUNDATIONOS_STORAGE_DEVICE_DEFAULT="mmcblk0"
FOUNDATIONOS_STORAGE_DEVICE ??= "${FOUNDATIONOS_STORAGE_DEVICE_DEFAULT}"

# Default storage device.
FOUNDATIONOS_STORAGE_DEVICE_PATH_DEFAULT = "/dev/${FOUNDATIONOS_STORAGE_DEVICE}"
FOUNDATIONOS_STORAGE_DEVICE_PATH ??= "${FOUNDATIONOS_STORAGE_DEVICE_PATH_DEFAULT}"

#Base name of the device holding partitions
FOUNDATIONOS_STORAGE_DEVICE_BASE_PATH_DEFAULT = "${FOUNDATIONOS_STORAGE_DEVICE_PATH}p"
FOUNDATIONOS_STORAGE_DEVICE_BASE_PATH ??= "${FOUNDATIONOS_STORAGE_DEVICE_BASE_PATH_DEFAULT}"

FOUNDATIONOS_PART_NUMBER_START = "1"

#Default filesystem in foundationos
FOUNDATIONOS_FSTYPE_DEFAULT = "ext4"
FOUNDATIONOS_FSTYPE ??= "${FOUNDATIONOS_FSTYPE_DEFAULT}"

#Partition alignment. Default to 4k.
FOUNDATIONOS_PARTITION_ALIGNMENT_DEFAULT = "4096"
FOUNDATIONOS_PARTITION_ALIGNMENT ??="${FOUNDATIONOS_PARTITION_ALIGNMENT_DEFAULT}"


# Total size of sdcard image.
FOUNDATIONOS_STORAGE_TOTAL_SIZE_MB_DEFAULT = "2048"
FOUNDATIONOS_STORAGE_TOTAL_SIZE_MB ??= "${FOUNDATIONOS_STORAGE_TOTAL_SIZE_MB_DEFAULT}"

FOUNDATIONOS_PTABLE_TYPE_DEFAULT = "gpt"
FOUNDATIONOS_PTABLE_TYPE ??= "${FOUNDATIONOS_PTABLE_TYPE_DEFAULT}"

#-------------------------------------------------------------------------------
#Boot partition
#-------------------------------------------------------------------------------
FOUNDATIONOS_BOOT_PART_NUMBER ??= "${FOUNDATIONOS_PART_NUMBER_START}"
FOUNDATIONOS_BOOT_PART_DEFAULT = "${FOUNDATIONOS_STORAGE_DEVICE_BASE_PATH}${FOUNDATIONOS_BOOT_PART_NUMBER}"
FOUNDATIONOS_BOOT_PART ??="${FOUNDATIONOS_BOOT_PART_DEFAULT}"

#Boot partiton size
FOUNDATIONOS_BOOT_PART_SIZE_MB_DEFAULT = "48"
FOUNDATIONOS_BOOT_PART_SIZE_MB ??= "${FOUNDATIONOS_BOOT_PART_SIZE_MB_DEFAULT}"

#Boot partiton fstype
FOUNDATIONOS_BOOT_PART_FSTYPE_DEFAULT = "vfat"
FOUNDATIONOS_BOOT_PART_FSTYPE ??= "${FOUNDATIONOS_BOOT_PART_FSTYPE_DEFAULT}"
#-------------------------------------------------------------------------------
#A/B rootfs partition
#-------------------------------------------------------------------------------
FOUNDATIONOS_ROOTFS_PART_A_PART_NUMBER ??= "${@eval('${FOUNDATIONOS_BOOT_PART_NUMBER} + 1')}"
FOUNDATIONOS_ROOTFS_PART_A_DEFAULT = "${FOUNDATIONOS_STORAGE_DEVICE_BASE_PATH}${FOUNDATIONOS_ROOTFS_PART_A_PART_NUMBER}"
FOUNDATIONOS_ROOTFS_PART_A ??= "${FOUNDATIONOS_ROOTFS_PART_A_DEFAULT}"

FOUNDATIONOS_ROOTFS_PART_A_FSTYPE_DEFAULT = "${FOUNDATIONOS_FSTYPE}"
FOUNDATIONOS_ROOTFS_PART_A_FSTYPE ??= "${FOUNDATIONOS_ROOTFS_PART_A_FSTYPE_DEFAULT}"

FOUNDATIONOS_ROOTFS_PART_A_LABEL_DEFAULT ??= "primary"
FOUNDATIONOS_ROOTFS_PART_A_LABEL ??= "${FOUNDATIONOS_ROOTFS_PART_A_LABEL_DEFAULT}"

FOUNDATIONOS_ROOTFS_PART_B_PART_NUMBER ??= "${@eval('${FOUNDATIONOS_ROOTFS_PART_A_PART_NUMBER} + 1')}"
FOUNDATIONOS_ROOTFS_PART_B_DEFAULT = "${FOUNDATIONOS_STORAGE_DEVICE_BASE_PATH}${FOUNDATIONOS_ROOTFS_PART_B_PART_NUMBER}"
FOUNDATIONOS_ROOTFS_PART_B ??= "${FOUNDATIONOS_ROOTFS_PART_B_DEFAULT}"

FOUNDATIONOS_ROOTFS_PART_B_FSTYPE_DEFAULT = "${FOUNDATIONOS_FSTYPE}"
FOUNDATIONOS_ROOTFS_PART_B_FSTYPE ??= "${FOUNDATIONOS_ROOTFS_PART_B_FSTYPE_DEFAULT}"

FOUNDATIONOS_ROOTFS_PART_B_LABEL_DEFAULT ??= "secondary"
FOUNDATIONOS_ROOTFS_PART_B_LABEL ??= "${FOUNDATIONOS_ROOTFS_PART_B_LABEL_DEFAULT}"
#-------------------------------------------------------------------------------
#Var partition
#-------------------------------------------------------------------------------#
FOUNDATIONOS_VAR_PART_NUMBER ??= "${@eval('${FOUNDATIONOS_ROOTFS_PART_B_PART_NUMBER} + 1')}"
FOUNDATIONOS_VAR_PART_DEFAULT = "${FOUNDATIONOS_STORAGE_DEVICE_BASE_PATH}${FOUNDATIONOS_VAR_PART_NUMBER}"
FOUNDATIONOS_VAR_PART ??= "${FOUNDATIONOS_VAR_PART_DEFAULT}"

#Var partition size
FOUNDATIONOS_VAR_PART_SIZE_MB_DEFAULT = "128"
FOUNDATIONOS_VAR_PART_SIZE_DEFAULT = "${@eval('${FOUNDATIONOS_VAR_PART_SIZE_MB} * 1024')}"
FOUNDATIONOS_VAR_PART_SIZE ??= "${FOUNDATIONOS_VAR_PART_SIZE_DEFAULT}"
FOUNDATIONOS_VAR_PART_SIZE_MB ??= "${FOUNDATIONOS_VAR_PART_SIZE_MB_DEFAULT}"

#var partition mount point
FOUNDATIONOS_VAR_PART_MOUNT_POINT_DEFAULT = "/var"
FOUNDATIONOS_VAR_PART_MOUNT_POINT ??= "${FOUNDATIONOS_VAR_PART_MOUNT_POINT_DEFAULT}"

FOUNDATIONOS_VAR_FSTYPE_DEFAULT = "${FOUNDATIONOS_FSTYPE}"
FOUNDATIONOS_VAR_FSTYPE ??= "${FOUNDATIONOS_ROOTFS_PART_A_FSTYPE_DEFAULT}"

FOUNDATIONOS_VAR_LABEL_DEFAULT ??= "var"
FOUNDATIONOS_VAR_LABEL ??= "${FOUNDATIONOS_VAR_LABEL_DEFAULT}"

#-------------------------------------------------------------------------------
#Reeftas data partition
#-------------------------------------------------------------------------------
FOUNDATIONOS_DATA_PART_NUMBER ??= "${@eval('${FOUNDATIONOS_VAR_PART_NUMBER} + 1')}"
FOUNDATIONOS_DATA_PART_DEFAULT = "${FOUNDATIONOS_STORAGE_DEVICE_BASE_PATH}${FOUNDATIONOS_DATA_PART_NUMBER}"
FOUNDATIONOS_DATA_PART ??= "${FOUNDATIONOS_DATA_PART_DEFAULT}"

#Data partiton size
FOUNDATIONOS_DATA_PART_SIZE_MB_DEFAULT = "512"
FOUNDATIONOS_DATA_PART_SIZE_DEFAULT = "${@eval('${FOUNDATIONOS_DATA_PART_SIZE_MB}')}"
FOUNDATIONOS_DATA_PART_SIZE_MB ??= "${FOUNDATIONOS_DATA_PART_SIZE_MB_DEFAULT}"
FOUNDATIONOS_DATA_PART_SIZE ??= "${FOUNDATIONOS_DATA_PART_SIZE_DEFAULT}"

#Reeftas data mount point
FOUNDATIONOS_DATA_MOUNT_POINT_DEFAULT = "/data"
FOUNDATIONOS_DATA_MOUNT_POINT ??= "${FOUNDATIONOS_DATA_MOUNT_POINT_DEFAULT}"

FOUNDATIONOS_DATA_FSTYPE_DEFAULT = "${FOUNDATIONOS_FSTYPE}"
FOUNDATIONOS_DATA_FSTYPE ??= "${FOUNDATIONOS_DATA_FSTYPE_DEFAULT}"

FOUNDATIONOS_DATA_LABEL_DEFAULT ??= "data"
FOUNDATIONOS_DATA_LABEL ??= "${FOUNDATIONOS_DATA_LABEL_DEFAULT}"

#----------------------------------------------------------------------
# Reeftas User and Group
#----------------------------------------------------------------------
FOUNDATIONOS_USER="foundationos"
FOUNDATIONOS_GROUP="foundationos"

include foundationos-uboot.inc
include foundationos-setup-install.inc
include foundationos-wic.inc
include foundationos-firsttime-boot.inc
